// Common IATA airline codes to airline names mapping
const AIRLINE_CODES = {
    // Major US Airlines
    AA: 'American Airlines',
    DL: 'Delta Air Lines',
    UA: 'United Airlines',
    WN: 'Southwest Airlines',
    B6: 'JetBlue Airways',
    AS: 'Alaska Airlines',
    NK: 'Spirit Airlines',
    F9: 'Frontier Airlines',
    HA: 'Hawaiian Airlines',
    G4: 'Allegiant Air',

    // Major International Airlines
    BA: 'British Airways',
    LH: 'Lufthansa',
    AF: 'Air France',
    KL: 'KLM Royal Dutch Airlines',
    IB: 'Iberia',
    AZ: 'ITA Airways',
    TP: 'TAP Air Portugal',
    SN: 'Brussels Airlines',
    OS: 'Austrian Airlines',
    LX: 'Swiss International Air Lines',
    SK: 'SAS Scandinavian Airlines',
    FI: 'Icelandair',
    AY: 'Finnair',
    LO: 'LOT Polish Airlines',
    OK: 'Czech Airlines',
    RO: 'TAROM',
    SU: 'Aeroflot',
    TK: 'Turkish Airlines',
    QR: 'Qatar Airways',
    EK: 'Emirates',
    EY: 'Etihad Airways',
    SV: 'Saudia',
    KU: 'Kuwait Airways',
    GF: 'Gulf Air',
    MS: 'EgyptAir',
    ET: 'Ethiopian Airlines',
    KQ: 'Kenya Airways',
    SA: 'South African Airways',
    AI: 'Air India',

    // Israeli Airlines
    LY: 'El Al Israel Airlines',
    '6H': 'Israir Airlines',
    IZ: 'Arkia Israeli Airlines',
    '8Z': 'Wings of Lebanon',
    '9W': 'Jet Airways',
    '6E': 'IndiGo',
    SG: 'SpiceJet',
    AI: 'Air India',
    CA: 'Air China',
    MU: 'China Eastern Airlines',
    CZ: 'China Southern Airlines',
    HU: 'Hainan Airlines',
    '3U': 'Sichuan Airlines',
    MF: 'Xiamen Airlines',
    FM: 'Shanghai Airlines',
    NH: 'All Nippon Airways',
    JL: 'Japan Airlines',
    KE: 'Korean Air',
    OZ: 'Asiana Airlines',
    TG: 'Thai Airways',
    VN: 'Vietnam Airlines',
    PR: 'Philippine Airlines',
    MH: 'Malaysia Airlines',
    SQ: 'Singapore Airlines',
    GA: 'Garuda Indonesia',
    QF: 'Qantas',
    NZ: 'Air New Zealand',
    AC: 'Air Canada',
    WS: 'WestJet',
    PD: 'Porter Airlines',
    F8: 'Flair Airlines',
    TS: 'Air Transat',
    RV: 'Air Canada Rouge',
    WG: 'Sunwing Airlines',
    WO: 'Swoop',
    Y9: 'Kish Air',
    IR: 'Iran Air',
    PK: 'Pakistan International Airlines',
    BG: 'Biman Bangladesh Airlines',
    UL: 'SriLankan Airlines',
    CX: 'Cathay Pacific',
    BR: 'EVA Air',
    CI: 'China Airlines',
    VZ: 'V Australia',
    DJ: 'Virgin Australia',
    VA: 'Virgin Australia',
    JQ: 'Jetstar Airways',
    TT: 'Tiger Airways Australia',
    TZ: 'Scoot',
    TR: 'Tigerair',
    AK: 'AirAsia',
    FD: 'Thai AirAsia',
    QZ: 'Indonesia AirAsia',
    D7: 'AirAsia X',
    Z2: 'AirAsia Zest',
    I5: 'AirAsia India',
    QJ: 'AirAsia Japan',
    XJ: 'Thai AirAsia X',
    XT: 'Indonesia AirAsia X',
    XZ: 'AirAsia X Thailand',
    XQ: 'SunExpress',
    PC: 'Pegasus Airlines',
    TK: 'Turkish Airlines',
    VY: 'Vueling',
    FR: 'Ryanair',
    U2: 'easyJet',
    DY: 'Norwegian Air Shuttle',
    SK: 'SAS Scandinavian Airlines',
    AY: 'Finnair',
    LO: 'LOT Polish Airlines',
    OK: 'Czech Airlines',
    RO: 'TAROM',
    SU: 'Aeroflot',
    S7: 'S7 Airlines',
    U6: 'Ural Airlines',
    UT: 'UTair Aviation',
    FV: 'Rossiya Airlines',
    DP: 'Pobeda',
    N4: 'Nordwind Airlines',
    I4: 'I-Fly',
    EO: 'Pegas Fly',
    Y7: 'NordStar',
    '5N': 'Smartavia',
    D2: 'Severstal Air Company',
    R3: 'Yakutia Airlines',
    ZF: 'Azur Air',
    EO: 'Pegas Fly',
    I4: 'I-Fly',
    N4: 'Nordwind Airlines',
    DP: 'Pobeda',
    FV: 'Rossiya Airlines',
    UT: 'UTair Aviation',
    U6: 'Ural Airlines',
    S7: 'S7 Airlines',
    SU: 'Aeroflot',
    RO: 'TAROM',
    OK: 'Czech Airlines',
    LO: 'LOT Polish Airlines',
    AY: 'Finnair',
    SK: 'SAS Scandinavian Airlines',
    DY: 'Norwegian Air Shuttle',
    U2: 'easyJet',
    FR: 'Ryanair',
    VY: 'Vueling',
    TK: 'Turkish Airlines',
    PC: 'Pegasus Airlines',
    XQ: 'SunExpress',
    XZ: 'AirAsia X Thailand',
    XT: 'Indonesia AirAsia X',
    XJ: 'Thai AirAsia X',
    QJ: 'AirAsia Japan',
    I5: 'AirAsia India',
    Z2: 'AirAsia Zest',
    D7: 'AirAsia X',
    QZ: 'Indonesia AirAsia',
    FD: 'Thai AirAsia',
    AK: 'AirAsia',
    TR: 'Tigerair',
    TZ: 'Scoot',
    TT: 'Tiger Airways Australia',
    JQ: 'Jetstar Airways',
    VA: 'Virgin Australia',
    DJ: 'Virgin Australia',
    VZ: 'V Australia',
    CI: 'China Airlines',
    BR: 'EVA Air',
    CX: 'Cathay Pacific',
    UL: 'SriLankan Airlines',
    BG: 'Biman Bangladesh Airlines',
    PK: 'Pakistan International Airlines',
    IR: 'Iran Air',
    Y9: 'Kish Air',
    WO: 'Swoop',
    WG: 'Sunwing Airlines',
    RV: 'Air Canada Rouge',
    TS: 'Air Transat',
    F8: 'Flair Airlines',
    PD: 'Porter Airlines',
    WS: 'WestJet',
    AC: 'Air Canada',
    NZ: 'Air New Zealand',
    QF: 'Qantas',
    GA: 'Garuda Indonesia',
    SQ: 'Singapore Airlines',
    MH: 'Malaysia Airlines',
    PR: 'Philippine Airlines',
    VN: 'Vietnam Airlines',
    TG: 'Thai Airways',
    OZ: 'Asiana Airlines',
    KE: 'Korean Air',
    JL: 'Japan Airlines',
    NH: 'All Nippon Airways',
    FM: 'Shanghai Airlines',
    MF: 'Xiamen Airlines',
    '3U': 'Sichuan Airlines',
    HU: 'Hainan Airlines',
    CZ: 'China Southern Airlines',
    MU: 'China Eastern Airlines',
    CA: 'Air China',
    AI: 'Air India',
    SG: 'SpiceJet',
    '6E': 'IndiGo',
    '9W': 'Jet Airways',
    AI: 'Air India',
    SA: 'South African Airways',
    KQ: 'Kenya Airways',
    ET: 'Ethiopian Airlines',
    MS: 'EgyptAir',
    GF: 'Gulf Air',
    KU: 'Kuwait Airways',
    SV: 'Saudia',
    EY: 'Etihad Airways',
    EK: 'Emirates',
    QR: 'Qatar Airways',
    TK: 'Turkish Airlines',
    SU: 'Aeroflot',
    RO: 'TAROM',
    OK: 'Czech Airlines',
    LO: 'LOT Polish Airlines',
    AY: 'Finnair',
    SK: 'SAS Scandinavian Airlines',
    LX: 'Swiss International Air Lines',
    OS: 'Austrian Airlines',
    SN: 'Brussels Airlines',
    TP: 'TAP Air Portugal',
    AZ: 'ITA Airways',
    IB: 'Iberia',
    KL: 'KLM Royal Dutch Airlines',
    AF: 'Air France',
    LH: 'Lufthansa',
    BA: 'British Airways',
    G4: 'Allegiant Air',
    HA: 'Hawaiian Airlines',
    F9: 'Frontier Airlines',
    NK: 'Spirit Airlines',
    AS: 'Alaska Airlines',
    B6: 'JetBlue Airways',
    WN: 'Southwest Airlines',
    UA: 'United Airlines',
    DL: 'Delta Air Lines',
    AA: 'American Airlines',
};

/**
 * Convert IATA airline code to airline name
 * @param {string} code - IATA airline code (e.g., 'B6', 'AA')
 * @returns {string} - Airline name or the original code if not found
 */
export function getAirlineName(code) {
    if (!code) return 'Unknown Airline';

    const airlineName = AIRLINE_CODES[code.toUpperCase()];
    return airlineName || code; // Return the code if no mapping found
}

/**
 * Get airline name with fallback to code
 * @param {string} code - IATA airline code
 * @returns {string} - Airline name or code
 */
export function formatAirline(code) {
    const name = getAirlineName(code);
    return name === code ? `${code} Airlines` : name;
}

export default AIRLINE_CODES;
